language: java
jdk:
- oraclejdk7
deploy:
  provider: heroku
  api_key:
    secure: oWKPyjs3l8XeAqDyVyKtcDXwFhg+HeUyUFFN37kR9g0kyykrd/VDyzURRG3ELx3sKeTUeSLjZmyzcyB3ElcD4x8w+33mDHvnCzbWx+vs/a6r0E3N+Y0g5vvHDjVQLCWKr12qzl0KjjEBp+pAq9/abzclbrF/zpWZqWhGii03mEo2SFFWdIaKmnZwXgi7nUCywLGE1AqigUA1spZWFXYLFN2dmzuxAoLcToDXaqzDqScOOSglf3aQUp81vRMp9uP5WpxKA72XgxQIjCvIVBzHvoSRLPyzs7RP9EHSCKOUFhPRcjB2VgkooOt9uXmW5Ggdh1cVYUvX2ppIKZWYTcS4tJXyXaEbTQQngX2GYIdrZfTTFuMTf7l0raxawKVSSiSAX7vEuVPhY6SjTLKubON4ph8spbcA7vm9l70FxdcKV9ITBv1TDzu4380JZhukoH198oowLu6hK3h3Nc1R2MVc7p3MeNqjcuSStEFbPkF06RDkVHKfnNmjbeB+BTGKTMf+fszI/iaXstKQspyt9MbkIQf0WR/ThjlMbZRhLii/HW8sqme3vItYIgAhWWTwo4B74cNgW6IeIeN/WXex4FyIvFUyd1Yz3lhWNVSfxhdcBuK7zkiKKM1OPTlJJWbz6GdxkwnJ7qmvwf6D8fegSdZa+A3ftCzM4quIdftjg+I/4js=
  app: onslocal
  on:
    repo: nesstest/onslocal
