language: java
jdk:
- oraclejdk7
deploy:
  provider: heroku
  api_key:
    secure: WwnrlZUgNb+a4XTHKEpOEZH9J/q+LZIDyqvi6V1FH3bh35mBzZhYeZ6I6XwMmZBJhPQdJCvQJcTBvo+vWtZLLgzn/Tfv3/tOfiPjIJnzhDZUxg8spZZIaPvuupgQBfcqJPRwozf7GZhuValtr6uNRrdoZt0U639/Bk0jGJ7GxpR5q2G31wRWR1BQWBH9UETIvYFkidtimpFYfgD5l8wdrIXHEgA2gMfdxruPCwI55GZyp5Tk7sLxhXcwm8P6JKgRKH9QnoZnQvGq2m47ee/7wBbEVfE+fW3oTwlEkTm4ZklKN4jXtSEaz44mKDaMCQSr99lqiPwwntU223MjqcvuvLM6P158E9wFHu59LP6BGLeMwzIoeqnZjy0ct6j3Jt0yqYcueRui53G5prO0Qm31nPJFwNyX/QnrxzxG7xFYVLWXOJ6MmblYWAesCUlbZsmjEc2LcPanVOJ66oPGyEfitf5Bonx8PRYy3+wzQDGxaKuSYnjfXlchCNC2GMnQUFgTj2Xlbt4km8Z4tO8PwLMYEqSX9ziSUzuIsDbSyEqgqz+qWzJYxKXl9qGEHmrfWtyg+p6LnOzmWw03jeltH12BfYPQtgUgbCdAI/ZtPOIJHWO3d/UPnxVXMcCBiGoJuylKQm/Lip0zsUqQ73Wl0J61EBfLxQU/4B+fML8bhCGF/2c=
  app: onslocal-js
  on:
    repo: nesstest/onslocal
    branch: jsBranch
branches:
  only:
  - jsBranch
