language: java
jdk:
- oraclejdk7
deploy:
  provider: heroku
  api_key:
    secure: xkocYwyWV/FUuT4qEOI2zcI0jJ9mw+nC+5B0vbxmna2JD+fqesDva4DgAHDYuYfZr45zbPV2Kg6n0DMOEjuvcIaoYtFF37yDvisdjft3v1H550hPS4x5eNZOlKlHhZpoplaeEo+9R6MLDNsY6X4NnlZMhyNTpFoVbYp/heh57L5vRalRNbfcQlsvM/rJXy0sTFCprcdHMdJEAV4RkfTwOvZ3pA1xM0h4siJx8eL2Zpg33ZKKjztLk3HZoONIDecFBPe5wrbCAdezAMPGbE/HPapzrUMYMv546CeLEZoLdPfs6Idtqcoz4XCSFhGO9bcgQ+YrtJtJqHYiacBKvn2kd398oi06Pjb12C60EYocVnQ/oUDzZwk6ik88G/xQMPfXZgz3xj1YFbxNHNCQyMNtD4qQmjB91ixgtYI/4pFZjAVyzzK8aq181Zrf9nzacJfD8MJVMX9saSgfq72cXnrj+5B1pmnXMnBDwoV8nbHsChxdEqsrr8I3Pe7IDHdmXUXBndzEnJUT5WCsywwt2abH9H3zJTTzsCCUY90Q5IcTAdey/chaTCi1ZFjXk9QF+VePebbHNbCEdp0vVjS4xcU8SOJvNRbYZvgR3uQZg6VByz11hOICCQj5UNdswV+NKDhRPeR88bw8528XC5flJw/aJxXd5jOwNX8byhWcX85qF7s=
  app: onslocal
  on:
    repo: nesstest/onslocal
